sudo: false

language: perl

perl:
    - "5.30"
    - "5.28"
    - "5.26"
    - "5.24"
    - "5.22"
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"

install:
    - cpanm Dist::Zilla
    - dzil authordeps --missing | cpanm -n
    - dzil listdeps --missing | cpanm -n

script:
    - dzil test --author --release
    - perl -Ilib t/*.t
